#!/usr/bin/env ansible-playbook
#- hosts: dataservers
- hosts: artifactory
  become: yes
  become_method: sudo
  roles:
   # - role: base_postgres
    - {role: base_postgres, continue_on_error: False}
